name: Conditional Pipeline on Label frontend

on:
  push:
    types: [labeled]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'frontend')
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Build
      run: npm run build
